/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ContinueHubIdeApi);
  }
}(this, function(expect, ContinueHubIdeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ContinueHubIdeApi.ListAssistants200ResponseInnerConfigResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListAssistants200ResponseInnerConfigResult', function() {
    it('should create an instance of ListAssistants200ResponseInnerConfigResult', function() {
      // uncomment below and update the code to test ListAssistants200ResponseInnerConfigResult
      //var instance = new ContinueHubIdeApi.ListAssistants200ResponseInnerConfigResult();
      //expect(instance).to.be.a(ContinueHubIdeApi.ListAssistants200ResponseInnerConfigResult);
    });

    it('should have the property config (base name: "config")', function() {
      // uncomment below and update the code to test the property config
      //var instance = new ContinueHubIdeApi.ListAssistants200ResponseInnerConfigResult();
      //expect(instance).to.be();
    });

    it('should have the property configLoadInterrupted (base name: "configLoadInterrupted")', function() {
      // uncomment below and update the code to test the property configLoadInterrupted
      //var instance = new ContinueHubIdeApi.ListAssistants200ResponseInnerConfigResult();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instance = new ContinueHubIdeApi.ListAssistants200ResponseInnerConfigResult();
      //expect(instance).to.be();
    });

  });

}));
