export const commonDocsRepos: string[] = [
  //   "https://github.com/freeCodeCamp/freeCodeCamp",
  "https://github.com/996icu/996.ICU",
  //   "https://github.com/vuejs/vue",
  //   "https://github.com/tensorflow/tensorflow",
  "https://github.com/sindresorhus/awesome",
  "https://github.com/twbs/bootstrap",
  //   "https://github.com/facebook/react",
  //   "https://github.com/torvalds/linux",
  //   "https://github.com/nodejs/node",
  //   "https://github.com/microsoft/vscode",
  //   "https://github.com/ohmyzsh/ohmyzsh",
  //   "https://github.com/kamranahmedse/developer-roadmap",
  //   "https://github.com/electron/electron",
  //   "https://github.com/apache/spark",
  //   "https://github.com/tensorflow/models",
  //   "https://github.com/ansible/ansible",
  //   "https://github.com/airbnb/javascript",
  //   "https://github.com/torvalds/subsurface-for-dirk",
  //   "https://github.com/scikit-learn/scikit-learn",
  //   "https://github.com/denoland/deno",
  //   "https://github.com/donnemartin/system-design-primer",
  //   "https://github.com/reduxjs/redux",
  //   "https://github.com/nvie/gitflow",
  //   "https://github.com/pallets/flask",
  //   "https://github.com/keras-team/keras",
  //   "https://github.com/spring-projects/spring-boot",
  //   "https://github.com/JetBrains/kotlin",
  //   "https://github.com/saltstack/salt",
  //   "https://github.com/apache/kafka",
  //   "https://github.com/moby/moby",
  //   "https://github.com/ansible/ansible-lint",
  //   "https://github.com/angular/angular",
  //   "https://github.com/microsoft/Terminal",
  //   "https://github.com/EbookFoundation/free-programming-books",
  //   "https://github.com/hashicorp/terraform",
  //   "https://github.com/grafana/grafana",
  //   "https://github.com/flutter/flutter",
  //   "https://github.com/kubernetes/kubernetes",
  "https://github.com/jquery/jquery",
  //   "https://github.com/laravel/laravel",
  //   "https://github.com/mrdoob/three.js",
  //   "https://github.com/prometheus/prometheus",
  //   "https://github.com/nltk/nltk",
  //   "https://github.com/facebook/react-native",
  //   "https://github.com/jekyll/jekyll",
  //   "https://github.com/wesbos/awesome-dev-podcasts",
  //   "https://github.com/expressjs/express",
  //   "https://github.com/elastic/elasticsearch",
  //   "https://github.com/RocketChat/Rocket.Chat",
  //   "https://github.com/open-source-labs/reactime",
];

export const commonDocsSites = [
  "https://docs.nestjs.com/",
  "https://go.dev/doc/",
  "https://clickhouse.com/docs",
];

export const failingDocsSites = [
  "https://www.tensorflow.org/api_docs",
  "https://docs.anthropic.com/en/docs",
  "https://www.rust-lang.org/learn",
];
