/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContinueError = ContinueError1;
export type Title = string;
export type Message = string;

export interface ContinueError1 {
  title: Title;
  message: Message;
  [k: string]: unknown;
}
