/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Default = string;
export type Summarize = string;
export type Edit = string;
export type Chat = string;
export type Saved = string;
export type Temperature = number | null;
export type SystemMessage = string | null;

/**
 * Main class that holds the current model configuration
 */
export interface Models {
  default: Default;
  summarize: Summarize;
  edit: Edit;
  chat: Chat;
  saved?: Saved;
  temperature?: Temperature;
  system_message?: SystemMessage;
  [k: string]: unknown;
}
