/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StepType = string | null;
export type Name = string | null;
export type Description = string | null;
export type Params = {
  [k: string]: unknown;
} | null;
export type Hide = boolean | null;
export type Depth = number | null;
export type Title = string;
export type Message = string;
export type Observations = Observation[] | null;
export type Logs = string[] | null;
export type History = StepDescription[];
export type Name1 = string;
export type Description1 = string;
export type ProviderTitle = string;
export type ItemId = string;
export type Content = string;
export type Editing = boolean;
export type Editable = boolean;
export type ContextItems = ContextItem[];
export type SessionId = string | null;

/**
 * Full session history and important state needed for autopilot to Continue
 */
export interface SessionState {
  history: History;
  context_items: ContextItems;
  session_id?: SessionId;
  [k: string]: unknown;
}
export interface StepDescription {
  step_type?: StepType;
  name?: Name;
  description?: Description;
  params: Params;
  hide?: Hide;
  depth?: Depth;
  error?: ContinueError | null;
  observations?: Observations;
  logs?: Logs;
  [k: string]: unknown;
}
export interface ContinueError {
  title: Title;
  message: Message;
  [k: string]: unknown;
}
export interface Observation {
  [k: string]: unknown;
}
/**
 * A ContextItem is a single item that is stored in the ContextManager.
 */
export interface ContextItem {
  description: ContextItemDescription;
  content: Content;
  editing?: Editing;
  editable?: Editable;
  [k: string]: unknown;
}
/**
 * A ContextItemDescription is a description of a ContextItem that is displayed to the user when they type '@'.
 *
 * The id can be used to retrieve the ContextItem from the ContextManager.
 */
export interface ContextItemDescription {
  name: Name1;
  description: Description1;
  id: ContextItemId;
  [k: string]: unknown;
}
/**
 * A ContextItemId is a unique identifier for a ContextItem.
 */
export interface ContextItemId {
  provider_title: ProviderTitle;
  item_id: ItemId;
  [k: string]: unknown;
}
