/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SlashCommandDescription = SlashCommandDescription1;
export type Name = string;
export type Description = string;

export interface SlashCommandDescription1 {
  name: Name;
  description: Description;
  [k: string]: unknown;
}
