---
name: 🐛 Bug report
description: Create a report to help us fix your bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        This will help to find the cause of the problem faster and require fewer follow-ups.
        ---
  - type: checkboxes
    attributes:
      label: Before submitting your Bug Report
      options:
        - label: I have checked that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: false
        - label: I confirm/suspect that this is a concrete bug. For questions and feedback, please join the [Continue Discord](https://discord.gg/NWtdYexhMs).
          required: false
        - label: I have checked the [Troubleshooting Guide](https://continue.dev/docs/troubleshooting).
          required: false
  - type: textarea
    attributes:
      label: Relevant Environment Infos
      description: |
        - **OS**: e.g. macOS 13.5.2
        - **Continue**: e.g. 0.0.398
        - **Python**: e.g. 3.8.5
        - **IDE**: e.g. VSCode 1.82.2
        - **Ollama**: e.g. v0.0.21
        - …
      value: |
        - OS:
        - Continue:
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Description
      description: |
        Please provide a clear and concise description of the bug.
      placeholder: |
        Short description
    validations:
      required: false
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem consistently. If possible, include a gif, screenshot, or video to better illustrate the problem.
      placeholder: |
        1. Go to …
        2. Click on …
        3. Scroll down to …
        4. See error
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: |
        To get the Continue server logs:
          1. <kbd>⌘ Command</kbd> + <kbd>⇧ Shift</kbd> + <kbd>P</kbd> (macOS) / <kbd>⌃ Control</kbd> + <kbd>⇧ Shift</kbd> + <kbd>P</kbd> (Windows)
          2. Search for and then select "Continue: View Continue Server Logs"
          3. Scroll to the bottom of `continue.log` and copy the last 100 lines or so

        To get the VS Code console logs:
          1. <kbd>⌘ Command</kbd> + <kbd>⇧ Shift</kbd> + <kbd>P</kbd> (macOS) / <kbd>⌃ Control</kbd> + <kbd>⇧ Shift</kbd> + <kbd>P</kbd> (Windows)
          2. Search for and then select "Developer: Toggle Developer Tools"
          3. Select Console
          4. Read the console logs

        If the problem is related to LLM prompting:
          1. Hover the problematic response in the Continue UI
          2. Click the "magnifying glass" icon
          3. Copy the contents of the `continue_logs.txt` file that opens
      render: Shell
