/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type History = History1;
export type Name = string;
export type Hide = boolean;
export type SystemMessage = string;
export type Depth = number;
export type Timeline = HistoryNode[];
export type CurrentIndex = number;

/**
 * A history of steps taken and their results
 */
export interface History1 {
  timeline: Timeline;
  current_index: CurrentIndex;
  [k: string]: unknown;
}
/**
 * A point in history, a list of which make up History
 */
export interface HistoryNode {
  step: Step;
  observation?: Observation;
  depth: Depth;
  [k: string]: unknown;
}
export interface Step {
  name?: Name;
  hide?: Hide;
  system_message?: SystemMessage;
  [k: string]: unknown;
}
export interface Observation {
  [k: string]: unknown;
}
