// Generated by continue

// Import modules
import { describe, expect, test } from "@jest/globals";
import { testIde } from "../test/fixtures";
import {
  TEST_DIR,
  addToTestDir,
  setUpTestDir,
  tearDownTestDir,
} from "../test/testDir";
import { shouldIgnore } from "./shouldIgnore";

// Test for the shouldIgnore function
describe("shouldIgnore", () => {
  beforeEach(() => {
    setUpTestDir();
  });

  afterEach(() => {
    tearDownTestDir();
  });

  test("should return true if a file is ignored by .gitignore", async () => {
    addToTestDir([
      ["/ignored-file.txt", "content"],
      ["/kept-file.txt", "content"],
      ["/.gitignore", "ignored-file.txt\nignored-folder/"],
      "/ignored-folder/",
      ["/ignored-folder/file.txt", "content"],
    ]);
    const result1 = await shouldIgnore(
      TEST_DIR + "/ignored-file.txt",
      TEST_DIR,
      testIde,
    );
    expect(result1).toBe(true);

    const result2 = await shouldIgnore(
      TEST_DIR + "/ignored-folder",
      TEST_DIR,
      testIde,
    );
    expect(result2).toBe(true);

    const result3 = await shouldIgnore(
      TEST_DIR + "/kept-file.txt",
      TEST_DIR,
      testIde,
    );
    expect(result3).toBe(false);
  });
});
