/**
 * Continue Hub IDE API
 * API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ListAssistants200ResponseInner from './models/ListAssistants200ResponseInner';
import ListAssistants200ResponseInnerConfigResult from './models/ListAssistants200ResponseInnerConfigResult';
import ListAssistants401Response from './models/ListAssistants401Response';
import ListAssistants404Response from './models/ListAssistants404Response';
import DefaultApi from './api/DefaultApi';


/**
* API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ContinueHubIdeApi = require('index'); // See note below*.
* var xxxSvc = new ContinueHubIdeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ContinueHubIdeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ContinueHubIdeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ContinueHubIdeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ListAssistants200ResponseInner model constructor.
     * @property {module:models/ListAssistants200ResponseInner}
     */
    ListAssistants200ResponseInner,

    /**
     * The ListAssistants200ResponseInnerConfigResult model constructor.
     * @property {module:models/ListAssistants200ResponseInnerConfigResult}
     */
    ListAssistants200ResponseInnerConfigResult,

    /**
     * The ListAssistants401Response model constructor.
     * @property {module:models/ListAssistants401Response}
     */
    ListAssistants401Response,

    /**
     * The ListAssistants404Response model constructor.
     * @property {module:models/ListAssistants404Response}
     */
    ListAssistants404Response,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
