# coding: utf-8

"""
    Continue Hub IDE API

    API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_assistant404_response import GetAssistant404Response

class TestGetAssistant404Response(unittest.TestCase):
    """GetAssistant404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssistant404Response:
        """Test GetAssistant404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssistant404Response`
        """
        model = GetAssistant404Response()
        if include_optional:
            return GetAssistant404Response(
                message = 'Assistant not found'
            )
        else:
            return GetAssistant404Response(
        )
        """

    def testGetAssistant404Response(self):
        """Test GetAssistant404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
