/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PersistedSessionInfo = PersistedSessionInfo1;
export type StepType = string;
export type Name = string;
export type Description = string;
export type Hide = boolean;
export type Depth = number;
export type Title = string;
export type Message = string;
export type Observations = Observation[];
export type Logs = string[];
export type History = StepDescription[];
export type Name1 = string;
export type Description1 = string;
export type ProviderTitle = string;
export type ItemId = string;
export type Content = string;
export type Editing = boolean;
export type Editable = boolean;
export type ContextItems = ContextItem[];
export type Title1 = string;
export type WorkspaceDirectory = string;
export type SessionId = string;

export interface PersistedSessionInfo1 {
  session_state: SessionState;
  title: Title1;
  workspace_directory: WorkspaceDirectory;
  session_id: SessionId;
  [k: string]: unknown;
}
/**
 * Full session history and important state needed for autopilot to Continue
 */
export interface SessionState {
  history: History;
  context_items: ContextItems;
  [k: string]: unknown;
}
export interface StepDescription {
  step_type: StepType;
  name: Name;
  description: Description;
  params: Params;
  hide: Hide;
  depth: Depth;
  error?: ContinueError;
  observations?: Observations;
  logs?: Logs;
  [k: string]: unknown;
}
export interface Params {
  [k: string]: unknown;
}
export interface ContinueError {
  title: Title;
  message: Message;
  [k: string]: unknown;
}
export interface Observation {
  [k: string]: unknown;
}
/**
 * A ContextItem is a single item that is stored in the ContextManager.
 */
export interface ContextItem {
  description: ContextItemDescription;
  content: Content;
  editing?: Editing;
  editable?: Editable;
  [k: string]: unknown;
}
/**
 * A ContextItemDescription is a description of a ContextItem that is displayed to the user when they type '@'.
 *
 * The id can be used to retrieve the ContextItem from the ContextManager.
 */
export interface ContextItemDescription {
  name: Name1;
  description: Description1;
  id: ContextItemId;
  [k: string]: unknown;
}
/**
 * A ContextItemId is a unique identifier for a ContextItem.
 */
export interface ContextItemId {
  provider_title: ProviderTitle;
  item_id: ItemId;
  [k: string]: unknown;
}
