/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Position = Position1;
export type Line = number;
export type Character = number;

export interface Position1 {
  line: Line;
  character: Character;
  [k: string]: unknown;
}
