/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RangeInFileWithContents = RangeInFileWithContents1;
export type Filepath = string;
export type Line = number;
export type Character = number;
export type Contents = string;

/**
 * A range in a file with the contents of the range.
 */
export interface RangeInFileWithContents1 {
  filepath: Filepath;
  range: Range;
  contents: Contents;
  [k: string]: unknown;
}
/**
 * A range in a file. 0-indexed.
 */
export interface Range {
  start: Position;
  end: Position;
  [k: string]: unknown;
}
export interface Position {
  line: Line;
  character: Character;
  [k: string]: unknown;
}
