/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SessionUpdate = SessionUpdate1;
export type Index = number;
export type Update = DeltaStep | SetStep | SessionUpdate1;
export type Name = string | null;
export type Description = string | null;
export type Observations = Observation[] | null;
export type Logs = string[] | null;
export type StepType = string | null;
export type Name1 = string | null;
export type Description1 = string | null;
export type Params = {
  [k: string]: unknown;
} | null;
export type Hide = boolean | null;
export type Depth = number | null;
export type Title = string;
export type Message = string;
export type Observations1 = Observation[] | null;
export type Logs1 = string[] | null;
export type Stop = boolean | null;

export interface SessionUpdate1 {
  index: Index;
  update: Update;
  stop?: Stop;
  [k: string]: unknown;
}
export interface DeltaStep {
  name?: Name;
  description?: Description;
  observations?: Observations;
  logs?: Logs;
  [k: string]: unknown;
}
export interface Observation {
  [k: string]: unknown;
}
export interface SetStep {
  step_type?: StepType;
  name?: Name1;
  description?: Description1;
  params?: Params;
  hide?: Hide;
  depth?: Depth;
  error?: ContinueError | null;
  observations?: Observations1;
  logs?: Logs1;
  [k: string]: unknown;
}
export interface ContinueError {
  title: Title;
  message: Message;
  [k: string]: unknown;
}
