name: Dev PR checks

on:
  pull_request:
    branches:
      - dev

jobs:
  tsc-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Check-out repository
      - name: Check-out repository
        uses: actions/checkout@v4

      # 2. Install npm dependencies
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        env:
          # https://github.com/microsoft/vscode-ripgrep/issues/9#issuecomment-643965333
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Type Check
        run: npm run typecheck

      - name: Lint
        run: npm run lint
