name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npx eslint .

      - name: Run Prettier
        run: |
          npx prettier --check .