name: PR checks

on:
  pull_request:
    branches:
      - main
    paths:
      - "extensions/vscode/**"
      - "core/**"
      - "gui/**"

jobs:
  tsc-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Cache root node_modules
        id: cache-root
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-root-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-root-

      - name: Cache extension node_modules
        id: cache-extension
        uses: actions/cache@v3
        with:
          path: extensions/vscode/node_modules
          key: ${{ runner.os }}-node-ext-${{ hashFiles('extensions/vscode/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-ext-

      - name: Cache core node_modules
        id: cache-core
        uses: actions/cache@v3
        with:
          path: core/node_modules
          key: ${{ runner.os }}-node-core-${{ hashFiles('core/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-core-

      - name: Cache gui node_modules
        id: cache-gui
        uses: actions/cache@v3
        with:
          path: gui/node_modules
          key: ${{ runner.os }}-node-gui-${{ hashFiles('gui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-gui-

      - name: Cache binary node_modules
        id: cache-binary
        uses: actions/cache@v3
        with:
          path: binary/node_modules
          key: ${{ runner.os }}-node-binary-${{ hashFiles('binary/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-binary-

      - name: root install
        run: |
          npm ci

      - name: extensions/vscode install
        run: |
          cd extensions/vscode
          npm ci
        env:
          # https://github.com/microsoft/vscode-ripgrep/issues/9#issuecomment-643965333
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: core install
        run: |
          cd core
          npm ci

      - name: gui install
        run: |
          cd gui
          npm ci

      - name: binary install
        run: |
          cd binary
          npm ci

      - name: extensions/vscode checks
        run: |
          cd extensions/vscode
          npx tsc --noEmit
          npm run lint

      - name: Install Xvfb for Linux and run end to end tests
        run: |
          sudo apt-get install -y xvfb # Install Xvfb
          Xvfb :99 & # Start Xvfb
          export DISPLAY=:99 # Export the display number to the environment
          cd extensions/vscode
          npm run package
          npm run e2e:ci

      - name: core checks
        run: |
          cd core
          npm ci
          npx tsc --noEmit
          npm run lint
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: gui checks
        run: |
          cd gui
          npx tsc --noEmit

      - name: binary checks
        run: |
          cd binary
          npx tsc --noEmit

      - name: Run core tests
        run: |
          cd core
          npm test

      - name: Run gui tests
        run: |
          cd gui
          npm test
