name: TypeScript Check

on:
  pull_request:
    branches:
      - main
      - preview
      - dev

jobs:
  tsc-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Check-out repository
      - name: Check-out repository
        uses: actions/checkout@v4

      # 2. Install npm dependencies
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Cache extension node_modules
        uses: actions/cache@v3
        with:
          path: extensions/vscode/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('extensions/vscode/package-lock.json') }}

      - name: Cache core node_modules
        uses: actions/cache@v3
        with:
          path: core/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('core/package-lock.json') }}

      - name: Cache gui node_modules
        uses: actions/cache@v3
        with:
          path: gui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('gui/package-lock.json') }}

      - name: Cache binary node_modules
        uses: actions/cache@v3
        with:
          path: binary/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('binary/package-lock.json') }}

      - name: Install extension Dependencies
        run: |
          cd extensions/vscode
          npm ci
        env:
          # https://github.com/microsoft/vscode-ripgrep/issues/9#issuecomment-643965333
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Install gui Dependencies
        run: |
          cd gui
          npm ci

      - name: Install Core Dependencies
        run: |
          cd core
          npm ci

      - name: Install Binary Dependencies
        run: |
          cd binary
          npm ci

      - name: tsc core
        run: |
          cd core
          npx tsc --noEmit

      - name: tsc extensions/vscode
        run: |
          cd extensions/vscode
          npx tsc --noEmit

      - name: tsc binary
        run: |
          cd binary
          npx tsc --noEmit

      - name: tsc gui
        run: |
          cd gui
          npx tsc --noEmit
